// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-DRZvVNZ50GHmdhkUjST3sqJbbCN1x7U',
    appId: '1:132056026039:web:3d035fefba413ebb29f632',
    messagingSenderId: '132056026039',
    projectId: 'mybprohr',
    authDomain: 'mybprohr.firebaseapp.com',
    databaseURL: 'https://mybprohr-default-rtdb.firebaseio.com',
    storageBucket: 'mybprohr.appspot.com',
    measurementId: 'G-K7JQF7F283',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ycG9lrqhgq4JD83BLd1fnuyDqtLUZw4',
    appId: '1:132056026039:android:4695447ac3c7406129f632',
    messagingSenderId: '132056026039',
    projectId: 'mybprohr',
    databaseURL: 'https://mybprohr-default-rtdb.firebaseio.com',
    storageBucket: 'mybprohr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBncumK9yMd07RVo4kn0nffPfN-Ju1pilA',
    appId: '1:132056026039:ios:470b15ff369df02929f632',
    messagingSenderId: '132056026039',
    projectId: 'mybprohr',
    databaseURL: 'https://mybprohr-default-rtdb.firebaseio.com',
    storageBucket: 'mybprohr.appspot.com',
    iosBundleId: 'com.example.multiVendorEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBncumK9yMd07RVo4kn0nffPfN-Ju1pilA',
    appId: '1:132056026039:ios:470b15ff369df02929f632',
    messagingSenderId: '132056026039',
    projectId: 'mybprohr',
    databaseURL: 'https://mybprohr-default-rtdb.firebaseio.com',
    storageBucket: 'mybprohr.appspot.com',
    iosBundleId: 'com.example.multiVendorEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-DRZvVNZ50GHmdhkUjST3sqJbbCN1x7U',
    appId: '1:132056026039:web:a7d49e338814f95d29f632',
    messagingSenderId: '132056026039',
    projectId: 'mybprohr',
    authDomain: 'mybprohr.firebaseapp.com',
    databaseURL: 'https://mybprohr-default-rtdb.firebaseio.com',
    storageBucket: 'mybprohr.appspot.com',
    measurementId: 'G-3FXXF012HK',
  );

}